### ISSUE TITLE
Thinning?

### ISSUE THREAD

**Issue by dchudz** [kapelner/bartMachine#1]
Have you thought about implementing thinning of the iterations? I'm thinking this would be a parameter that lets you specify that only every `n` iterations (e.g. `n=10`) are saved after burn-in.

I've only played with your implementation a little bit, but in a toy example, 10k post-burn-in iterations got me an effective sample size of around 250. I'd be almost as well off (and my memory would be much better off) keeping every 10th iteration.

(P.S. Thanks for doing this. I'm really excited about bartMachine!)

**Comment by rsparapa** [comment]
Thinning is definitely best done on the java side.  However, you can manage the memory by running bartMachine in a loop, thin each posterior and pull it all together.  It will not be as efficient, but if you are running out of RAM (like me ;o) then this might help.  Here is a wrapper that I created for classification which should give you an idea of what I am talking about.

pbartMachine=function( 
                      x.train, y.train, x.test=matrix(0.0,0,0),
                      k=2.0, power=2.0, base=.95,
                      ntree=200, numcut=100,
                      ndpost=1000, nskip=250, keepevery=1, mc.cores=1,
                      seed=99, alpha_0 = 1, do_ard = 1, do_prior = 1
                      )
{
    library(dartMachine)

    set_bart_machine_num_cores(mc.cores)

    n = length(y.train)

    if(n!=nrow(x.train))
        stop('The length of y.train and the number of rows in x.train must be identical')
    
    if(nrow(x.test)==0)
        stop('To generate the posterior, you must specify x.test')

    post <- list()
    post$x.test <- x.test
    thin <- seq(keepevery, ndpost, by=keepevery)

    for(h in 1:keepevery) {
        res = bartMachine(
            X=as.data.frame(x.train), y=factor(y.train),
            num_trees=ntree, num_burn_in=nskip,
            num_iterations_after_burn_in=ndpost,
            alpha=base, beta=power, k=k, 
            seed=seed, alpha_0 = alpha_0, do_ard = do_ard, do_prior = do_prior
        )

        if(h==1) {
            res$prob.test <- bart_machine_get_posterior(res, as.data.frame(x.test))$y_hat_posterior_samples[ , thin]
            post$prob.test <- t(res$prob.test)
        }
        else {
            res$prob.test <- bart_machine_get_posterior(res, as.data.frame(x.test))$y_hat_posterior_samples[ , thin]
            post$prob.test <- rbind(post$prob.test, t(res$prob.test))
        }

        rm(res)
        gc()
    }
        
    post$prob.test.mean <- apply(post$prob.test, 2, mean)
    
    return(post)
}

**Comment by tjmckinley** [comment]
Hi all, 

I was desperately searching for a way to thin `bartMachine` chains and came across this thread. I appreciate that it's been closed, but I was wondering if anyone had found a solution (or if there were any plans to implement this)? 

Currently I am running into all the problems that David highlights above with a dataset/model that I'm working on. I can get good convergence and mixing using either `BART` or `dbarts` by running multiple chains of 50,000 iterations and then thinning and combining to get 2,000 final samples with good ESS and Rhat values. 

However, `bartMachine` offers the opportunity to deal with missing predictor information using MIA, which I would like to try instead of the complete-case analysis I'm currently implementing. I can apply Rodney's approach above, but that only thins the outputs, and doesn't help if I want to use the saved trees to use bartMachine's variable selection approach say, which will run if I generate only 2,000 samples but not 50,000. Hence if I could thin the trees then this might solve this issue. I need to run a lot of models and a lot of replicates for robust optimism estimates etc., so I really need a memory efficient solution. Else I'll have to stick with the complete-case I think.

I would try to figure out the implementation myself but I know zero Java, so I'm at a bit of an impasse. I appreciate all the work done on this (and `BART` and `dbarts`) and I think this would be a really useful feature to have.

Cheers,

TJ
